//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmission
    {
        public int AdmissionID { get; set; }
        public string PatientCode { get; set; }
        public string AdmissionReason { get; set; }
        public string AdmissionTime { get; set; }
        public string AdmissionDate { get; set; }
        public string DischargeTime { get; set; }
        public string DischargeDate { get; set; }
        public string DischargeReason { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> BedID { get; set; }
    }
}
