//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlternative
    {
        public int AlternativeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> GenericID { get; set; }
    }
}
