//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrugChart
    {
        public int DrugChartID { get; set; }
        public string Description { get; set; }
        public string Dosage { get; set; }
        public int PatientID { get; set; }
        public int MedicationID { get; set; }
        public Nullable<System.DateTime> DateGiven { get; set; }
        public Nullable<System.TimeSpan> TimeGive { get; set; }
    }
}
