//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicalAidDetail
    {
        public int MedicalAidDetailID { get; set; }
        public Nullable<int> MedicalAidID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PlanName { get; set; }
        public string MedicalAidNumber { get; set; }
        public string HeadMemberName { get; set; }
        public string HeadMemberID { get; set; }
        public string HeadMemberNumber { get; set; }
    }
}
