//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNextOfKin
    {
        public int NextOfKinID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Relation { get; set; }
        public string ContactNum { get; set; }
        public string Email { get; set; }
    }
}
