//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> PatientAdmissionID { get; set; }
        public Nullable<int> PrescriberID { get; set; }
        public Nullable<int> ReceivingNurseID { get; set; }
        public Nullable<int> MedicationID { get; set; }
        public string PaymentConfirmed { get; set; }
    }
}
