//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScriptMed
    {
        public int ScriptMedsID { get; set; }
        public Nullable<int> MedicationID { get; set; }
        public Nullable<int> ScriptID { get; set; }
        public Nullable<int> Refills { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string RxNotes { get; set; }
    }
}
