//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWard
    {
        public int WardID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TelephoneNum { get; set; }
        public int HospitalID { get; set; }
    }
}
